name: 'chromatic'
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm i -g yarn
      - run: yarn build-storybook 
      - uses: chromaui/action@v1
        with: 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static